### ISSUE TITLE
업무일지 페이징

### ISSUE THREAD

**Issue by wayne-kim** [wayne-kim/basic_board-Spring_Postgresql_MyBatis_BootStrap-#4]
업무일지에 페이징 기능 없습니다.

게시판 소스를 참조하면 충분히 만들 수 있을겁니다.

참조 소스는 
**java**
BoardController
PageMaker
BoardVO
Criteria -> SearchCriteria
BoardDAO
BoardDAOImpl
BoardService
BoardServiceImpl
**mapper**
boardMapper
**view** 
views/board/list.jsp
javascript 내용이 워낙 적어서 list.jsp 에 다 있습니다.

타일 기능 궁금하면 다음 타일 jsp 파일을 보면 됩니다.
views/include/header.jsp
views/include/footer.jsp

**Comment by 5pecia1** [comment]
제가 페이지 만들어 보겠습니다.
급한 거 아니시면 마엘스톤은 9월 17일로 하겠습니다.

**Comment by wayne-kim** [comment]
핵심 기능 완성O
